version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
          name: Run NPM lint
    #   - run:
    #       command: npm run test
    #       name: Run NPM tests
workflows:
  node-tests:
    jobs:
      - lint
      - node/test
