version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
jobs:
  check:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
          name: Run NPM linter
      - run:
          command: npm run test
          name: Run NPM tests
workflows:
  node-tests:
    jobs:
      - check
      - heroku/deploy-via-git:
          requires:
            - check
